/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.csiii.memorizingmachine;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 * 
 * @author konda_957835
 */
public class GUI extends javax.swing.JFrame {
    /**
     * Creates new form TextOverlayAction
     */
    User user;
    //this is a placeholder until the memorizingGoal has all the information to be placed in a users goals
    Memorizing_Goal tmpGoal = new Memorizing_Goal();
    TextOverlay currOverlay = new TextOverlay("");
    StyledDocument doc;
    Memorizing_Goal currGoal = new Memorizing_Goal();
    //the text the user needs to type
    String memorizeText;
    
    public GUI() throws BadLocationException { 
        initComponents();
        //components should be set after the initComponents()
        user = new User();
        homePage.setVisible(true);
        TextOverlayTask.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createMemoryGoal_ = new javax.swing.JDialog();
        backgroundPopUp = new javax.swing.JPanel();
        CreateMemoryGoalPanel = new javax.swing.JPanel();
        titleGoal = new javax.swing.JLabel();
        next_JButton_ = new javax.swing.JButton();
        plainTextLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        plainTextBox = new javax.swing.JTextArea();
        Books = new javax.swing.JComboBox<>();
        Chapter = new javax.swing.JComboBox<>();
        beginVerse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endVerse = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        goalConfirm = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();
        GoalNamejTextField = new javax.swing.JTextField();
        goalNameLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        create_jButton = new javax.swing.JButton();
        numDaysJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        TextOverlayTask = new javax.swing.JPanel();
        MemorizeText = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        selectGoal = new javax.swing.JComboBox<>();
        confirmGoal = new javax.swing.JButton();
        noGoalsWarning = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dashboard = new javax.swing.JMenu();
        newGoal = new javax.swing.JMenu();

        createMemoryGoal_.setMinimumSize(new java.awt.Dimension(400, 300));
        createMemoryGoal_.setResizable(false);
        createMemoryGoal_.setSize(new java.awt.Dimension(400, 300));

        backgroundPopUp.setBackground(new java.awt.Color(102, 255, 204));
        backgroundPopUp.setLayout(new java.awt.CardLayout());

        CreateMemoryGoalPanel.setBackground(new java.awt.Color(204, 255, 204));
        CreateMemoryGoalPanel.setPreferredSize(new java.awt.Dimension(594, 434));

        titleGoal.setText("Create your memorizing goal: ");

        next_JButton_.setText("Next");
        next_JButton_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_JButton_MouseClicked(evt);
            }
        });

        plainTextLabel.setText("Enter plain text to memorize:");

        plainTextBox.setColumns(20);
        plainTextBox.setRows(5);
        jScrollPane2.setViewportView(plainTextBox);

        Books.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genesis" }));

        Chapter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));

        beginVerse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3" }));

        jLabel3.setText(":");

        jLabel4.setText("-");

        endVerse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5" }));

        jLabel1.setText("Use the drop downs or the plain text option");

        javax.swing.GroupLayout CreateMemoryGoalPanelLayout = new javax.swing.GroupLayout(CreateMemoryGoalPanel);
        CreateMemoryGoalPanel.setLayout(CreateMemoryGoalPanelLayout);
        CreateMemoryGoalPanelLayout.setHorizontalGroup(
            CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                .addGroup(CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                                .addComponent(titleGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(next_JButton_))
                            .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                                .addGroup(CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                                        .addComponent(Books, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Chapter, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(beginVerse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endVerse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 226, Short.MAX_VALUE))))
                    .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(plainTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CreateMemoryGoalPanelLayout.setVerticalGroup(
            CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateMemoryGoalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_JButton_))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateMemoryGoalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Books, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(endVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(plainTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        backgroundPopUp.add(CreateMemoryGoalPanel, "card4");

        javax.swing.GroupLayout createMemoryGoal_Layout = new javax.swing.GroupLayout(createMemoryGoal_.getContentPane());
        createMemoryGoal_.getContentPane().setLayout(createMemoryGoal_Layout);
        createMemoryGoal_Layout.setHorizontalGroup(
            createMemoryGoal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPopUp, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        createMemoryGoal_Layout.setVerticalGroup(
            createMemoryGoal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPopUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        goalConfirm.setMinimumSize(new java.awt.Dimension(405, 126));
        goalConfirm.setUndecorated(true);
        goalConfirm.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        createLabel.setText("Create Your Memorizing Goal:");

        goalNameLabel.setText("Memorizing Goal Name: ");

        dayLabel.setText("How many days do you want to take:");

        create_jButton.setText("Create");
        create_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_jButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(createLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(create_jButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numDaysJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(goalNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(GoalNamejTextField)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLabel)
                    .addComponent(create_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel)
                    .addComponent(numDaysJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goalNameLabel)
                    .addComponent(GoalNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout goalConfirmLayout = new javax.swing.GroupLayout(goalConfirm.getContentPane());
        goalConfirm.getContentPane().setLayout(goalConfirmLayout);
        goalConfirmLayout.setHorizontalGroup(
            goalConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        goalConfirmLayout.setVerticalGroup(
            goalConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 440));

        background.setBackground(new java.awt.Color(153, 204, 255));
        background.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        background.setMaximumSize(new java.awt.Dimension(600, 440));
        background.setMinimumSize(new java.awt.Dimension(600, 440));
        background.setPreferredSize(new java.awt.Dimension(600, 440));
        background.setLayout(new java.awt.CardLayout());

        TextOverlayTask.setBackground(new java.awt.Color(153, 153, 255));
        TextOverlayTask.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.magenta, java.awt.Color.magenta));
        TextOverlayTask.setMaximumSize(new java.awt.Dimension(600, 440));
        TextOverlayTask.setMinimumSize(new java.awt.Dimension(600, 440));
        TextOverlayTask.setPreferredSize(new java.awt.Dimension(600, 440));

        MemorizeText.setEditable(false);
        MemorizeText.setBackground(new java.awt.Color(204, 255, 255));
        MemorizeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MemorizeTextKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Click the box and type over the overlay.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Each time you type the portion correctly,");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(" blanks will replace words and you must type over them");

        javax.swing.GroupLayout TextOverlayTaskLayout = new javax.swing.GroupLayout(TextOverlayTask);
        TextOverlayTask.setLayout(TextOverlayTaskLayout);
        TextOverlayTaskLayout.setHorizontalGroup(
            TextOverlayTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextOverlayTaskLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MemorizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(TextOverlayTaskLayout.createSequentialGroup()
                .addGroup(TextOverlayTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextOverlayTaskLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(TextOverlayTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)))
                    .addGroup(TextOverlayTaskLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextOverlayTaskLayout.setVerticalGroup(
            TextOverlayTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextOverlayTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MemorizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        background.add(TextOverlayTask, "card2");

        homePage.setBackground(new java.awt.Color(153, 204, 255));
        homePage.setFocusTraversalPolicyProvider(true);

        selectGoal.setActionCommand("");

        confirmGoal.setText("Go");
        confirmGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmGoalActionPerformed(evt);
            }
        });

        noGoalsWarning.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        noGoalsWarning.setForeground(new java.awt.Color(0, 51, 204));
        noGoalsWarning.setText("You have no memorizing goals, click \"New Goal\"");

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noGoalsWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePageLayout.createSequentialGroup()
                        .addComponent(selectGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(confirmGoal)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmGoal))
                .addGap(37, 37, 37)
                .addComponent(noGoalsWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        background.add(homePage, "card3");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jMenuBar1.add(dashboard);

        newGoal.setText("New Goal");
        newGoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGoalMouseClicked(evt);
            }
        });
        jMenuBar1.add(newGoal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//this is the go button on the homepage
    private void confirmGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmGoalActionPerformed

        if(selectGoal.getItemCount() == 0)
        {
            noGoalsWarning.setText("You must create a memorizing goal first, click \"New Goal\"");
            return;
        }
        homePage.setVisible(false);
        CreateMemoryGoalPanel.setVisible(false);
        int goalIndex = selectGoal.getSelectedIndex();
        //gets the goal from the goal index in the users arraylist of goals and then gets the text to memorize from that goal
        currGoal = user.get_Goal(goalIndex);
        currGoal.setDropdownIndex(goalIndex);
        String memorizeText = user.get_Goal(goalIndex).nextTask().getText();
        MemorizeText.setText("");
        doc = MemorizeText.getStyledDocument();
        SimpleAttributeSet uncompletedFont = new SimpleAttributeSet();
        StyleConstants.setForeground(uncompletedFont, Color.GRAY);
        try {
            //this makes the doc hold the text before the user begins typing
            doc.insertString(doc.getLength(), memorizeText, uncompletedFont);
        } catch (BadLocationException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        currOverlay = new TextOverlay(memorizeText);
     
  
        TextOverlayTask.setVisible(true);
    }//GEN-LAST:event_confirmGoalActionPerformed

    private void newGoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGoalMouseClicked
        // TODO add your handling code here:
        homePage.setVisible(true);
        TextOverlayTask.setVisible(false);
        createMemoryGoal_.setVisible(true);
    }//GEN-LAST:event_newGoalMouseClicked

    private void MemorizeTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemorizeTextKeyPressed
        //if the user has already finished the challenge, the cannot type anymore
        //shouldn't just test if done typing, done typing means just typed one way thorugh
        if(currOverlay.doneTyping() && currOverlay.wordsLeftToRemove() == 0)
        {
          
            // all of the owrds must be turned into blanks
            return;
           
        }
        char charTyped = evt.getKeyChar();
        //if the key the user types is not the expected char, exit the function
        if (currOverlay.getCurrChar() != charTyped)
        {
            return;
        }
       
        //this if statement means that if the expected char was a ' ' and the user entered it (because of the if statement above)
        if(currOverlay.getCurrChar() == ' ')
        {
            //then the next char cannot be a space
            currOverlay.setSpace(false);
            //a space counts as a correctChar - because completed/uncompleted portions include spaces - so the number of correctChars must be incremented
            currOverlay.incCorrectChars();
        }
        else
        {
            //if the char we are on is a space, we don't want to increment the index, since this applies to the index of the current word
            //and spaces are not in words, hence, we increment the index in this else statement
            //the index will only be incremented if the user types the expected char and that expected char is NOT a space
            currOverlay.incIndex();       
        }
        
        try
        {
            SimpleAttributeSet completedFont = new SimpleAttributeSet();
            StyleConstants.setForeground(completedFont, new Color(0, 208, 14));
            StyleConstants.setBold(completedFont, true);
            
            SimpleAttributeSet cursorFont = new SimpleAttributeSet();
            StyleConstants.setForeground(cursorFont, new Color(21, 98, 207));
            
            
            //sets the Memorize text to blank so a blank document can be acquired
            MemorizeText.setText("");
            doc = MemorizeText.getStyledDocument();
            //doc length is 0, it first inserts the completed poriton 
            doc.insertString(doc.getLength(), currOverlay.getCompeltedPortion(), completedFont);
            //by inserting at doLength, we insert the uncompleted portion right after the completed portion
            SimpleAttributeSet uncompletedFont = new SimpleAttributeSet();
            StyleConstants.setForeground(uncompletedFont, Color.GRAY);
            doc.insertString(doc.getLength(), "|", cursorFont);
            doc.insertString(doc.getLength(), currOverlay.getUncompletedPortion(), uncompletedFont);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        //when the user has finished typing
        if(currOverlay.doneTyping())
        {
            if(currOverlay.wordsLeftToRemove() == 0)
            {
                System.out.println("tasksLeft: " + currGoal.tasksLeft());
                SimpleAttributeSet feedbackFont = new SimpleAttributeSet();
                StyleConstants.setForeground(feedbackFont, new Color(0, 0, 200));
                MemorizeText.setText("");
                doc = MemorizeText.getStyledDocument();
                try {
                    if(currGoal.tasksLeft() == 0)
                    {
                         doc.insertString(doc.getLength(), "Congragulations, you have completed the entire memorizing goal. Your memorizing goal will now be removed from your dashboard's drop down list. Please press \"Dashboard\" on the menu above.", feedbackFont);
                         selectGoal.removeItemAt(currGoal.getDropdownIndex());
                         user.removeGoal(currGoal.getDropdownIndex());
                         if(selectGoal.getItemCount() == 0)
                         {
                             noGoalsWarning.setText("You have no memorizing goals, click \"New Goal\"");
                         }
                    }
                    else
                    {
                        doc.insertString(doc.getLength(), "Congragulations, you have completed the task, please press \"Dashboard\" on the menu above", feedbackFont);
                    }
                } catch (BadLocationException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                currOverlay.remove(2);
                //the reset method is called so that the text shows the blanks
                currOverlay.reset();
                MemorizeText.setText("");
                doc = MemorizeText.getStyledDocument();
                SimpleAttributeSet uncompletedFont = new SimpleAttributeSet();
                StyleConstants.setForeground(uncompletedFont, Color.GRAY);
                try {
                    //the doc now shows the text with blanks
                    doc.insertString(doc.getLength(), currOverlay.getUncompletedPortion(), uncompletedFont);
                } catch (BadLocationException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_MemorizeTextKeyPressed

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked

        homePage.setVisible(true);
        TextOverlayTask.setVisible(false);
        createMemoryGoal_.setVisible(false);
        MemorizeText.setText("");
    }//GEN-LAST:event_dashboardMouseClicked
//the next button is located on the first page of creating a new memorizing goal
    private void next_JButton_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_JButton_MouseClicked
        // TODO add your handling code here:
        createMemoryGoal_.setVisible(false);
        goalConfirm.setVisible(true);
        tmpGoal.setText(plainTextBox.getText());
        //clears the text box after text has been extracted
        plainTextBox.setText("");
        GoalNamejTextField.setText("");
        numDaysJTextField.setText("1");
    }//GEN-LAST:event_next_JButton_MouseClicked

    private void create_jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_jButtonMouseClicked
        // TODO add your handling code here:
        //can find a better way to update this, the warning about having no memorizing goals should be gone the FIRST time a goal is added, this does it everytime a goal is added
        noGoalsWarning.setText("");
        goalConfirm.setVisible(false);
        //this should be made fool proof (if users don't type in numbers
        tmpGoal.setDays(Integer.parseInt(numDaysJTextField.getText()));
        tmpGoal.setName(GoalNamejTextField.getText());
        //adds the new goal
        user.add_Goal(tmpGoal);
        tmpGoal = new Memorizing_Goal();
        //after a new goal is created, it is addded to the available goals that can be selected
        selectGoal.addItem(GoalNamejTextField.getText());
    }//GEN-LAST:event_create_jButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                   
                } catch (BadLocationException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Books;
    private javax.swing.JComboBox<String> Chapter;
    private javax.swing.JPanel CreateMemoryGoalPanel;
    private javax.swing.JTextField GoalNamejTextField;
    private javax.swing.JTextPane MemorizeText;
    private javax.swing.JPanel TextOverlayTask;
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundPopUp;
    private javax.swing.JComboBox<String> beginVerse;
    private javax.swing.JButton confirmGoal;
    private javax.swing.JLabel createLabel;
    private javax.swing.JDialog createMemoryGoal_;
    private javax.swing.JButton create_jButton;
    private javax.swing.JMenu dashboard;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JComboBox<String> endVerse;
    private javax.swing.JDialog goalConfirm;
    private javax.swing.JLabel goalNameLabel;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu newGoal;
    private javax.swing.JButton next_JButton_;
    private javax.swing.JLabel noGoalsWarning;
    private javax.swing.JTextField numDaysJTextField;
    private javax.swing.JTextArea plainTextBox;
    private javax.swing.JLabel plainTextLabel;
    private javax.swing.JComboBox<String> selectGoal;
    private javax.swing.JLabel titleGoal;
    // End of variables declaration//GEN-END:variables
    
}
